### PR TITLE
Add size dependent performance plots for separator

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by maxnoe** [comment]
separator-7

separator-3

separator-4

**Comment by LukasNickel** [comment]
Looks useful to plot separate histograms, but is there an intrinsic motivation to do exactly two plots and split exactly at the median?

**Comment by maxnoe** [comment]
> but is there an intrinsic motivation to do exactly two plots and split exactly at the median?

No, just that the median splits the dataset in half by definition, so is a good way to get *two* plots.

**Comment by LukasNickel** [comment]
Thats fair.
For a quantitative analysis, you would look at the ROC or compute your own metrics anyway, so thats good enough for visual inspection I guess.

**Comment by LukasNickel** [comment]
Could you add the `size_column` to the `examples/config_separator.yaml`, so that the lines are run by the tests?

**Comment by maxnoe** [comment]
good point.

**Comment by LukasNickel** [comment]
> Could you add the `size_column` to the `examples/config_separator.yaml`, so that the lines are run by the tests?

Do we not want to do this anymore?

**Pull request closed without merging**
